// Code generated by pigeon; DO NOT EDIT.

package recipe

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Recipe",
			pos:  position{line: 3, col: 1, offset: 20},
			expr: &actionExpr{
				pos: position{line: 3, col: 11, offset: 30},
				run: (*parser).callonRecipe1,
				expr: &seqExpr{
					pos: position{line: 3, col: 11, offset: 30},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 3, col: 11, offset: 30},
							label: "require",
							expr: &zeroOrOneExpr{
								pos: position{line: 3, col: 19, offset: 38},
								expr: &ruleRefExpr{
									pos:  position{line: 3, col: 19, offset: 38},
									name: "Require",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 3, col: 28, offset: 47},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 3, col: 30, offset: 49},
							label: "lines",
							expr: &ruleRefExpr{
								pos:  position{line: 3, col: 36, offset: 55},
								name: "Lines",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 3, col: 42, offset: 61},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 3, col: 44, offset: 63},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Lines",
			pos:  position{line: 22, col: 1, offset: 487},
			expr: &actionExpr{
				pos: position{line: 22, col: 10, offset: 496},
				run: (*parser).callonLines1,
				expr: &seqExpr{
					pos: position{line: 22, col: 10, offset: 496},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 22, col: 10, offset: 496},
							label: "head",
							expr: &zeroOrMoreExpr{
								pos: position{line: 22, col: 15, offset: 501},
								expr: &actionExpr{
									pos: position{line: 22, col: 16, offset: 502},
									run: (*parser).callonLines5,
									expr: &seqExpr{
										pos: position{line: 22, col: 16, offset: 502},
										exprs: []any{
											&labeledExpr{
												pos:   position{line: 22, col: 16, offset: 502},
												label: "val",
												expr: &zeroOrOneExpr{
													pos: position{line: 22, col: 20, offset: 506},
													expr: &ruleRefExpr{
														pos:  position{line: 22, col: 20, offset: 506},
														name: "Pair",
													},
												},
											},
											&ruleRefExpr{
												pos:  position{line: 22, col: 26, offset: 512},
												name: "_",
											},
											&ruleRefExpr{
												pos:  position{line: 22, col: 28, offset: 514},
												name: "NL",
											},
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 22, col: 53, offset: 539},
							label: "tail",
							expr: &zeroOrOneExpr{
								pos: position{line: 22, col: 58, offset: 544},
								expr: &ruleRefExpr{
									pos:  position{line: 22, col: 58, offset: 544},
									name: "Pair",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Require",
			pos:  position{line: 31, col: 1, offset: 675},
			expr: &actionExpr{
				pos: position{line: 31, col: 12, offset: 686},
				run: (*parser).callonRequire1,
				expr: &seqExpr{
					pos: position{line: 31, col: 12, offset: 686},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 31, col: 12, offset: 686},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 31, col: 14, offset: 688},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 31, col: 18, offset: 692},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 31, col: 20, offset: 694},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 31, col: 25, offset: 699},
								name: "RequireContent",
							},
						},
						&labeledExpr{
							pos:   position{line: 31, col: 40, offset: 714},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 31, col: 45, offset: 719},
								expr: &actionExpr{
									pos: position{line: 31, col: 46, offset: 720},
									run: (*parser).callonRequire10,
									expr: &seqExpr{
										pos: position{line: 31, col: 46, offset: 720},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 31, col: 46, offset: 720},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 31, col: 48, offset: 722},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 31, col: 52, offset: 726},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 31, col: 54, offset: 728},
												label: "val",
												expr: &ruleRefExpr{
													pos:  position{line: 31, col: 58, offset: 732},
													name: "RequireContent",
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 31, col: 95, offset: 769},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 31, col: 97, offset: 771},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
						&ruleRefExpr{
							pos:  position{line: 31, col: 101, offset: 775},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 31, col: 103, offset: 777},
							name: "NL",
						},
					},
				},
			},
		},
		{
			name: "RequireContent",
			pos:  position{line: 35, col: 1, offset: 836},
			expr: &choiceExpr{
				pos: position{line: 35, col: 19, offset: 854},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 35, col: 19, offset: 854},
						run: (*parser).callonRequireContent2,
						expr: &seqExpr{
							pos: position{line: 35, col: 19, offset: 854},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 35, col: 19, offset: 854},
									label: "ky",
									expr: &ruleRefExpr{
										pos:  position{line: 35, col: 22, offset: 857},
										name: "Key",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 35, col: 26, offset: 861},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 35, col: 28, offset: 863},
									val:        "=",
									ignoreCase: false,
									want:       "\"=\"",
								},
								&ruleRefExpr{
									pos:  position{line: 35, col: 32, offset: 867},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 35, col: 34, offset: 869},
									label: "value",
									expr: &ruleRefExpr{
										pos:  position{line: 35, col: 40, offset: 875},
										name: "Value",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 36, col: 19, offset: 952},
						run: (*parser).callonRequireContent11,
						expr: &labeledExpr{
							pos:   position{line: 36, col: 19, offset: 952},
							label: "ky",
							expr: &ruleRefExpr{
								pos:  position{line: 36, col: 22, offset: 955},
								name: "Key",
							},
						},
					},
				},
			},
		},
		{
			name: "Key",
			pos:  position{line: 38, col: 1, offset: 999},
			expr: &actionExpr{
				pos: position{line: 38, col: 8, offset: 1006},
				run: (*parser).callonKey1,
				expr: &labeledExpr{
					pos:   position{line: 38, col: 8, offset: 1006},
					label: "val",
					expr: &oneOrMoreExpr{
						pos: position{line: 38, col: 12, offset: 1010},
						expr: &charClassMatcher{
							pos:        position{line: 38, col: 12, offset: 1010},
							val:        "[a-zA-Z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Pair",
			pos:  position{line: 40, col: 1, offset: 1055},
			expr: &actionExpr{
				pos: position{line: 40, col: 9, offset: 1063},
				run: (*parser).callonPair1,
				expr: &seqExpr{
					pos: position{line: 40, col: 9, offset: 1063},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 40, col: 9, offset: 1063},
							label: "ky",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 12, offset: 1066},
								name: "Key",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 40, col: 16, offset: 1070},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 40, col: 18, offset: 1072},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 40, col: 22, offset: 1076},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 40, col: 24, offset: 1078},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 30, offset: 1084},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "Path",
			pos:  position{line: 42, col: 1, offset: 1144},
			expr: &actionExpr{
				pos: position{line: 42, col: 9, offset: 1152},
				run: (*parser).callonPath1,
				expr: &labeledExpr{
					pos:   position{line: 42, col: 9, offset: 1152},
					label: "val",
					expr: &oneOrMoreExpr{
						pos: position{line: 42, col: 13, offset: 1156},
						expr: &charClassMatcher{
							pos:        position{line: 42, col: 13, offset: 1156},
							val:        "[^ [\\]]",
							chars:      []rune{' ', '[', ']'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name: "AttributeGetter",
			pos:  position{line: 44, col: 1, offset: 1218},
			expr: &actionExpr{
				pos: position{line: 44, col: 20, offset: 1237},
				run: (*parser).callonAttributeGetter1,
				expr: &seqExpr{
					pos: position{line: 44, col: 20, offset: 1237},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 44, col: 20, offset: 1237},
							val:        "->",
							ignoreCase: false,
							want:       "\"->\"",
						},
						&labeledExpr{
							pos:   position{line: 44, col: 25, offset: 1242},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 29, offset: 1246},
								name: "Key",
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionCall",
			pos:  position{line: 46, col: 1, offset: 1271},
			expr: &actionExpr{
				pos: position{line: 46, col: 17, offset: 1287},
				run: (*parser).callonFunctionCall1,
				expr: &seqExpr{
					pos: position{line: 46, col: 17, offset: 1287},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 46, col: 17, offset: 1287},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 21, offset: 1291},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 23, offset: 1293},
							label: "path",
							expr: &choiceExpr{
								pos: position{line: 46, col: 29, offset: 1299},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 46, col: 29, offset: 1299},
										name: "Path",
									},
									&ruleRefExpr{
										pos:  position{line: 46, col: 36, offset: 1306},
										name: "String",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 46, col: 44, offset: 1314},
							label: "params",
							expr: &zeroOrOneExpr{
								pos: position{line: 46, col: 51, offset: 1321},
								expr: &ruleRefExpr{
									pos:  position{line: 46, col: 51, offset: 1321},
									name: "FunctionParams",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 67, offset: 1337},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 69, offset: 1339},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 73, offset: 1343},
							label: "attr",
							expr: &zeroOrOneExpr{
								pos: position{line: 46, col: 78, offset: 1348},
								expr: &ruleRefExpr{
									pos:  position{line: 46, col: 78, offset: 1348},
									name: "AttributeGetter",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionParams",
			pos:  position{line: 54, col: 1, offset: 1550},
			expr: &actionExpr{
				pos: position{line: 54, col: 19, offset: 1568},
				run: (*parser).callonFunctionParams1,
				expr: &seqExpr{
					pos: position{line: 54, col: 19, offset: 1568},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 54, col: 19, offset: 1568},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 54, col: 21, offset: 1570},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 26, offset: 1575},
								name: "Pair",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 31, offset: 1580},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 54, col: 36, offset: 1585},
								expr: &actionExpr{
									pos: position{line: 54, col: 37, offset: 1586},
									run: (*parser).callonFunctionParams8,
									expr: &seqExpr{
										pos: position{line: 54, col: 37, offset: 1586},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 54, col: 37, offset: 1586},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 54, col: 39, offset: 1588},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 54, col: 43, offset: 1592},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 54, col: 45, offset: 1594},
												label: "val",
												expr: &ruleRefExpr{
													pos:  position{line: 54, col: 49, offset: 1598},
													name: "Pair",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 58, col: 1, offset: 1680},
			expr: &actionExpr{
				pos: position{line: 58, col: 10, offset: 1689},
				run: (*parser).callonValue1,
				expr: &seqExpr{
					pos: position{line: 58, col: 10, offset: 1689},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 58, col: 10, offset: 1689},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 58, col: 16, offset: 1695},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 58, col: 16, offset: 1695},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 25, offset: 1704},
										name: "Multiline",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 37, offset: 1716},
										name: "FunctionCall",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 58, col: 52, offset: 1731},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 60, col: 1, offset: 1754},
			expr: &actionExpr{
				pos: position{line: 60, col: 11, offset: 1764},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 60, col: 11, offset: 1764},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 60, col: 11, offset: 1764},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&labeledExpr{
							pos:   position{line: 60, col: 15, offset: 1768},
							label: "content",
							expr: &oneOrMoreExpr{
								pos: position{line: 60, col: 23, offset: 1776},
								expr: &ruleRefExpr{
									pos:  position{line: 60, col: 23, offset: 1776},
									name: "StringContent",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 60, col: 38, offset: 1791},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "Multiline",
			pos:  position{line: 61, col: 1, offset: 1831},
			expr: &actionExpr{
				pos: position{line: 61, col: 14, offset: 1844},
				run: (*parser).callonMultiline1,
				expr: &seqExpr{
					pos: position{line: 61, col: 14, offset: 1844},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 61, col: 14, offset: 1844},
							val:        "\"\"",
							ignoreCase: false,
							want:       "\"\\\"\\\"\"",
						},
						&labeledExpr{
							pos:   position{line: 61, col: 21, offset: 1851},
							label: "content",
							expr: &zeroOrMoreExpr{
								pos: position{line: 61, col: 29, offset: 1859},
								expr: &ruleRefExpr{
									pos:  position{line: 61, col: 29, offset: 1859},
									name: "MultilineContent",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 61, col: 47, offset: 1877},
							val:        "\"\"",
							ignoreCase: false,
							want:       "\"\\\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "StringContent",
			pos:  position{line: 63, col: 1, offset: 1921},
			expr: &choiceExpr{
				pos: position{line: 63, col: 18, offset: 1938},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 63, col: 18, offset: 1938},
						name: "StringInterpolation",
					},
					&actionExpr{
						pos: position{line: 63, col: 40, offset: 1960},
						run: (*parser).callonStringContent3,
						expr: &seqExpr{
							pos: position{line: 63, col: 40, offset: 1960},
							exprs: []any{
								&notExpr{
									pos: position{line: 63, col: 40, offset: 1960},
									expr: &litMatcher{
										pos:        position{line: 63, col: 41, offset: 1961},
										val:        "${",
										ignoreCase: false,
										want:       "\"${\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 63, col: 46, offset: 1966},
									label: "chr",
									expr: &charClassMatcher{
										pos:        position{line: 63, col: 50, offset: 1970},
										val:        "[^\"\\n\\r]",
										chars:      []rune{'"', '\n', '\r'},
										ignoreCase: false,
										inverted:   true,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MultilineContent",
			pos:  position{line: 64, col: 1, offset: 1999},
			expr: &choiceExpr{
				pos: position{line: 64, col: 21, offset: 2019},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 64, col: 21, offset: 2019},
						name: "StringInterpolation",
					},
					&actionExpr{
						pos: position{line: 64, col: 44, offset: 2042},
						run: (*parser).callonMultilineContent3,
						expr: &seqExpr{
							pos: position{line: 64, col: 44, offset: 2042},
							exprs: []any{
								&notExpr{
									pos: position{line: 64, col: 44, offset: 2042},
									expr: &litMatcher{
										pos:        position{line: 64, col: 45, offset: 2043},
										val:        "\"\"",
										ignoreCase: false,
										want:       "\"\\\"\\\"\"",
									},
								},
								&notExpr{
									pos: position{line: 64, col: 52, offset: 2050},
									expr: &litMatcher{
										pos:        position{line: 64, col: 53, offset: 2051},
										val:        "${",
										ignoreCase: false,
										want:       "\"${\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 64, col: 58, offset: 2056},
									label: "chr",
									expr: &anyMatcher{
										line: 64, col: 62, offset: 2060,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "StringInterpolation",
			pos:  position{line: 66, col: 1, offset: 2084},
			expr: &actionExpr{
				pos: position{line: 66, col: 24, offset: 2107},
				run: (*parser).callonStringInterpolation1,
				expr: &seqExpr{
					pos: position{line: 66, col: 24, offset: 2107},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 66, col: 24, offset: 2107},
							val:        "${",
							ignoreCase: false,
							want:       "\"${\"",
						},
						&ruleRefExpr{
							pos:  position{line: 66, col: 29, offset: 2112},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 66, col: 31, offset: 2114},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 35, offset: 2118},
								name: "StringValue",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 66, col: 47, offset: 2130},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 66, col: 49, offset: 2132},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "StringValue",
			pos:  position{line: 68, col: 1, offset: 2157},
			expr: &actionExpr{
				pos: position{line: 68, col: 16, offset: 2172},
				run: (*parser).callonStringValue1,
				expr: &seqExpr{
					pos: position{line: 68, col: 16, offset: 2172},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 68, col: 16, offset: 2172},
							label: "ky",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 19, offset: 2175},
								name: "Key",
							},
						},
						&labeledExpr{
							pos:   position{line: 68, col: 23, offset: 2179},
							label: "attr",
							expr: &zeroOrOneExpr{
								pos: position{line: 68, col: 28, offset: 2184},
								expr: &ruleRefExpr{
									pos:  position{line: 68, col: 28, offset: 2184},
									name: "AttributeGetter",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NL",
			pos:  position{line: 75, col: 1, offset: 2344},
			expr: &choiceExpr{
				pos: position{line: 75, col: 7, offset: 2350},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 75, col: 7, offset: 2350},
						val:        "\n",
						ignoreCase: false,
						want:       "\"\\n\"",
					},
					&litMatcher{
						pos:        position{line: 75, col: 14, offset: 2357},
						val:        "\r\n",
						ignoreCase: false,
						want:       "\"\\r\\n\"",
					},
				},
			},
		},
		{
			name: "WS",
			pos:  position{line: 76, col: 1, offset: 2364},
			expr: &charClassMatcher{
				pos:        position{line: 76, col: 7, offset: 2370},
				val:        "[ \\t]",
				chars:      []rune{' ', '\t'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 78, col: 1, offset: 2377},
			expr: &zeroOrMoreExpr{
				pos: position{line: 78, col: 19, offset: 2395},
				expr: &choiceExpr{
					pos: position{line: 78, col: 20, offset: 2396},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 78, col: 20, offset: 2396},
							name: "Comment",
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 30, offset: 2406},
							name: "WS",
						},
					},
				},
			},
		},
		{
			name:        "Comment",
			displayName: "\"comment\"",
			pos:         position{line: 79, col: 1, offset: 2411},
			expr: &seqExpr{
				pos: position{line: 79, col: 22, offset: 2432},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 79, col: 22, offset: 2432},
						val:        "#",
						ignoreCase: false,
						want:       "\"#\"",
					},
					&oneOrMoreExpr{
						pos: position{line: 79, col: 26, offset: 2436},
						expr: &charClassMatcher{
							pos:        position{line: 79, col: 26, offset: 2436},
							val:        "[^\\n\\r]",
							chars:      []rune{'\n', '\r'},
							ignoreCase: false,
							inverted:   true,
						},
					},
					&andExpr{
						pos: position{line: 79, col: 35, offset: 2445},
						expr: &choiceExpr{
							pos: position{line: 79, col: 37, offset: 2447},
							alternatives: []any{
								&ruleRefExpr{
									pos:  position{line: 79, col: 37, offset: 2447},
									name: "NL",
								},
								&ruleRefExpr{
									pos:  position{line: 79, col: 42, offset: 2452},
									name: "EOF",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 81, col: 1, offset: 2458},
			expr: &notExpr{
				pos: position{line: 81, col: 8, offset: 2465},
				expr: &anyMatcher{
					line: 81, col: 9, offset: 2466,
				},
			},
		},
	},
}

func (c *current) onRecipe1(require, lines any) (any, error) {
	result := &Recipe{}
	if require != nil {
		result.RequireAttributes = collectPairs(require.([]pair))
	} else {
		result.RequireAttributes = map[string]Buildable{}
	}

	// attrs := make([]pair, 0, len(lines.([]pair)))
	// for _, t := range lines.([]any) {
	//	if t != nil {
	//		attrs = append(attrs, t.(pair))
	// 	}
	// }
	result.Attributes = collectPairs(lines.([]pair))

	return result, nil
}

func (p *parser) callonRecipe1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRecipe1(stack["require"], stack["lines"])
}

func (c *current) onLines5(val any) (any, error) {
	return val, nil
}

func (p *parser) callonLines5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLines5(stack["val"])
}

func (c *current) onLines1(head, tail any) (any, error) {
	slc := toAnySlice[pair](head.([]any))
	if tail == nil {
		return slc, nil
	}

	return append(slc, tail.(pair)), nil
}

func (p *parser) callonLines1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLines1(stack["head"], stack["tail"])
}

func (c *current) onRequire10(val any) (any, error) {
	return val, nil
}

func (p *parser) callonRequire10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRequire10(stack["val"])
}

func (c *current) onRequire1(head, tail any) (any, error) {
	return headTail[pair](head, tail.([]any)), nil
}

func (p *parser) callonRequire1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRequire1(stack["head"], stack["tail"])
}

func (c *current) onRequireContent2(ky, value any) (any, error) {
	return pair{ky.(string), value.(Buildable)}, nil
}

func (p *parser) callonRequireContent2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRequireContent2(stack["ky"], stack["value"])
}

func (c *current) onRequireContent11(ky any) (any, error) {
	return pair{ky.(string), nil}, nil
}

func (p *parser) callonRequireContent11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRequireContent11(stack["ky"])
}

func (c *current) onKey1(val any) (any, error) {
	return asString(val), nil
}

func (p *parser) callonKey1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKey1(stack["val"])
}

func (c *current) onPair1(ky, value any) (any, error) {
	return pair{ky.(string), value.(Buildable)}, nil
}

func (p *parser) callonPair1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPair1(stack["ky"], stack["value"])
}

func (c *current) onPath1(val any) (any, error) {
	return &RecipeStringLiteral{asString(val)}, nil
}

func (p *parser) callonPath1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPath1(stack["val"])
}

func (c *current) onAttributeGetter1(val any) (any, error) {
	return val, nil
}

func (p *parser) callonAttributeGetter1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAttributeGetter1(stack["val"])
}

func (c *current) onFunctionCall1(path, params, attr any) (any, error) {

	call := &RecipeFunction{path.(Buildable), collectPairs(toAnySlice[pair](params.([]any)))}
	if attr == nil {
		return call, nil
	}
	return &RecipeGetter{call, attr.(string)}, nil
}

func (p *parser) callonFunctionCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionCall1(stack["path"], stack["params"], stack["attr"])
}

func (c *current) onFunctionParams8(val any) (any, error) {
	return val, nil
}

func (p *parser) callonFunctionParams8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionParams8(stack["val"])
}

func (c *current) onFunctionParams1(head, tail any) (any, error) {
	return headTail[any](head, tail.([]any)), nil
}

func (p *parser) callonFunctionParams1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionParams1(stack["head"], stack["tail"])
}

func (c *current) onValue1(val any) (any, error) {
	return val, nil
}

func (p *parser) callonValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onString1(content any) (any, error) {
	return makeString(content), nil
}

func (p *parser) callonString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1(stack["content"])
}

func (c *current) onMultiline1(content any) (any, error) {
	return makeString(content), nil
}

func (p *parser) callonMultiline1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiline1(stack["content"])
}

func (c *current) onStringContent3(chr any) (any, error) {
	return chr, nil
}

func (p *parser) callonStringContent3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringContent3(stack["chr"])
}

func (c *current) onMultilineContent3(chr any) (any, error) {
	return chr, nil
}

func (p *parser) callonMultilineContent3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultilineContent3(stack["chr"])
}

func (c *current) onStringInterpolation1(val any) (any, error) {
	return val, nil
}

func (p *parser) callonStringInterpolation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringInterpolation1(stack["val"])
}

func (c *current) onStringValue1(ky, attr any) (any, error) {
	if attr == nil {
		return &RecipeReference{ky.(string)}, nil
	}
	return &RecipeGetter{&RecipeReference{ky.(string)}, attr.(string)}, nil
}

func (p *parser) callonStringValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringValue1(stack["ky"], stack["attr"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
